#!/usr/bin/env node

/**
 * Guardian Pull Request Creation
 * 
 * Creates a pull request for the Guardian-generated changes
 * with comprehensive description and validation summaries.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

class GuardianPRCreator {
  constructor(options = {}) {
    this.branchName = options.branch || '';
    this.targetBranch = options.target || 'main';
    this.changeRequest = options.request || '';
    this.workingDir = process.cwd();
  }

  log(message) {
    console.log(`[CREATE-PR] ${message}`);
  }

  loadGuardianReports() {
    const reports = {
      plan: null,
      patch: null,
      staticValidation: null,
      runtimeValidation: null,
      critiques: []
    };

    // Load plan
    const planPath = path.join(this.workingDir, 'guardian-plan.json');
    if (fs.existsSync(planPath)) {
      reports.plan = JSON.parse(fs.readFileSync(planPath, 'utf8'));
    }

    // Load patch info
    const patchPath = path.join(this.workingDir, 'guardian-patch.json');
    if (fs.existsSync(patchPath)) {
      reports.patch = JSON.parse(fs.readFileSync(patchPath, 'utf8'));
    }

    // Load static validation
    const staticPath = path.join(this.workingDir, 'guardian-static-validation.json');
    if (fs.existsSync(staticPath)) {
      reports.staticValidation = JSON.parse(fs.readFileSync(staticPath, 'utf8'));
    }

    // Load runtime validation
    const runtimePath = path.join(this.workingDir, 'guardian-runtime-validation.json');
    if (fs.existsSync(runtimePath)) {
      reports.runtimeValidation = JSON.parse(fs.readFileSync(runtimePath, 'utf8'));
    }

    // Load critique reports
    for (let i = 1; i <= 3; i++) {
      const critiquePath = path.join(this.workingDir, `guardian-critique-cycle-${i}.json`);
      if (fs.existsSync(critiquePath)) {
        reports.critiques.push(JSON.parse(fs.readFileSync(critiquePath, 'utf8')));
      }
    }

    return reports;
  }

  generatePRTitle(reports) {
    const request = this.changeRequest || reports.plan?.metadata?.request || 'Guardian Agent Changes';
    
    // Truncate and sanitize for PR title
    const sanitized = request.replace(/[^\w\s-]/g, '').trim();
    const truncated = sanitized.length > 60 ? sanitized.substring(0, 57) + '...' : sanitized;
    
    return `🤖 Guardian: ${truncated}`;
  }

  generatePRDescription(reports) {
    const sections = [];

    // Header
    sections.push('# Guardian Agent - Automated Change Generation');
    sections.push('');
    sections.push('This pull request was automatically generated by the Guardian Agent workflow.');
    sections.push('');

    // Change Request
    sections.push('## 📝 Change Request');
    sections.push('```');
    sections.push(this.changeRequest || reports.plan?.metadata?.request || 'No change request specified');
    sections.push('```');
    sections.push('');

    // Summary
    sections.push('## 📊 Summary');
    const summary = this.generateSummary(reports);
    sections.push(summary);
    sections.push('');

    // Changes Made
    if (reports.patch?.changes) {
      sections.push('## 🔄 Changes Made');
      for (const change of reports.patch.changes) {
        const icon = change.type === 'create' ? '➕' : change.type === 'modify' ? '✏️' : '❌';
        sections.push(`- ${icon} \`${change.type}\` ${change.path}`);
      }
      sections.push('');
    }

    // Validation Results
    sections.push('## ✅ Validation Results');
    sections.push(this.generateValidationSection(reports));
    sections.push('');

    // Refinements (if any)
    if (reports.critiques.length > 0) {
      sections.push('## 🔧 Refinements Applied');
      sections.push(this.generateRefinementSection(reports.critiques));
      sections.push('');
    }

    // Technical Details
    sections.push('## 🔍 Technical Details');
    sections.push(this.generateTechnicalDetails(reports));
    sections.push('');

    // Guardian Metadata
    sections.push('## 🤖 Guardian Metadata');
    sections.push(this.generateMetadataSection(reports));
    sections.push('');

    // Safety and Review
    sections.push('## ⚠️ Review Guidelines');
    sections.push('- [ ] Review all generated changes for correctness');
    sections.push('- [ ] Verify functionality works as expected');
    sections.push('- [ ] Check for any security implications');
    sections.push('- [ ] Ensure changes follow project conventions');
    sections.push('- [ ] Test in development environment');
    sections.push('');

    // Footer
    sections.push('---');
    sections.push('*Generated by Guardian Agent v1.0.0*');
    sections.push(`*Branch: \`${this.branchName}\`*`);
    sections.push(`*Timestamp: ${new Date().toISOString()}*`);

    return sections.join('\n');
  }

  generateSummary(reports) {
    const lines = [];
    
    // Validation status
    const staticPassed = reports.staticValidation?.summary?.success || false;
    const runtimePassed = reports.runtimeValidation?.summary?.overallSuccess || false;
    
    lines.push(`- **Static Validation**: ${staticPassed ? '✅ Passed' : '❌ Failed'}`);
    lines.push(`- **Runtime Validation**: ${runtimePassed ? '✅ Passed' : '❌ Failed'}`);
    
    // Refinement cycles
    if (reports.critiques.length > 0) {
      lines.push(`- **Refinement Cycles**: ${reports.critiques.length}`);
    }
    
    // Change count
    const changeCount = reports.patch?.changes?.length || 0;
    lines.push(`- **Files Changed**: ${changeCount}`);
    
    // Validation level
    const validationLevel = reports.plan?.metadata?.validationLevel || 'unknown';
    lines.push(`- **Validation Level**: ${validationLevel}`);

    return lines.join('\n');
  }

  generateValidationSection(reports) {
    const lines = [];
    
    // Static validation
    if (reports.staticValidation) {
      const static_ = reports.staticValidation;
      lines.push('### Static Validation');
      lines.push(`- **Status**: ${static_.summary.success ? '✅ Passed' : '❌ Failed'}`);
      lines.push(`- **Checks Passed**: ${static_.summary.passed}`);
      lines.push(`- **Checks Failed**: ${static_.summary.failed}`);
      lines.push(`- **Warnings**: ${static_.summary.warnings}`);
      
      if (static_.results.failed.length > 0) {
        lines.push('- **Failed Checks**:');
        for (const failure of static_.results.failed.slice(0, 3)) {
          lines.push(`  - ${failure.name}: ${failure.error}`);
        }
        if (static_.results.failed.length > 3) {
          lines.push(`  - ... and ${static_.results.failed.length - 3} more`);
        }
      }
      lines.push('');
    }

    // Runtime validation
    if (reports.runtimeValidation) {
      const runtime = reports.runtimeValidation;
      lines.push('### Runtime Validation');
      lines.push(`- **Status**: ${runtime.summary.overallSuccess ? '✅ Passed' : '❌ Failed'}`);
      lines.push(`- **Smoke Test**: ${runtime.summary.smokeTestPassed ? '✅' : '❌'}`);
      lines.push(`- **Test Suite**: ${runtime.summary.testSuitePassed ? '✅' : '❌'}`);
      lines.push(`- **Performance**: ${runtime.summary.performanceTestPassed ? '✅' : '❌'}`);
      lines.push(`- **Warnings**: ${runtime.summary.warningCount}`);
      lines.push('');
    }

    return lines.join('\n');
  }

  generateRefinementSection(critiques) {
    const lines = [];
    
    for (let i = 0; i < critiques.length; i++) {
      const critique = critiques[i];
      lines.push(`### Cycle ${i + 1}`);
      lines.push(`- **Issues Found**: ${critique.analysis.issues.length}`);
      lines.push(`- **Refinements Applied**: ${critique.refinementResults.length}`);
      lines.push(`- **Success Rate**: ${critique.refinementResults.filter(r => r.success).length}/${critique.refinementResults.length}`);
      lines.push(`- **Recommendation**: ${critique.recommendation.message}`);
      lines.push('');
    }

    return lines.join('\n');
  }

  generateTechnicalDetails(reports) {
    const lines = [];
    
    if (reports.plan) {
      lines.push(`- **Framework**: ${reports.plan.repository.packageJson.framework || 'unknown'}`);
      lines.push(`- **Build System**: ${reports.plan.repository.buildSystem.system || 'unknown'}`);
      lines.push(`- **Testing Framework**: ${reports.plan.repository.testingFramework.framework || 'none'}`);
      lines.push(`- **Linting**: ${reports.plan.repository.lintingSetup.hasEslint ? 'ESLint configured' : 'No linting'}`);
    }
    
    if (reports.patch) {
      lines.push(`- **Branch**: \`${reports.patch.branchName}\``);
      lines.push(`- **Change Complexity**: ${reports.patch.analysis.complexity}`);
      lines.push(`- **Change Type**: ${reports.patch.analysis.type}`);
    }

    return lines.join('\n');
  }

  generateMetadataSection(reports) {
    const lines = [];
    
    lines.push('```json');
    const metadata = {
      guardianVersion: '1.0.0',
      workflow: 'guardian-agent',
      timestamp: new Date().toISOString(),
      branchName: this.branchName,
      targetBranch: this.targetBranch,
      validationLevel: reports.plan?.metadata?.validationLevel,
      refinementCycles: reports.critiques.length,
      validationsPassed: {
        static: reports.staticValidation?.summary?.success || false,
        runtime: reports.runtimeValidation?.summary?.overallSuccess || false
      }
    };
    lines.push(JSON.stringify(metadata, null, 2));
    lines.push('```');

    return lines.join('\n');
  }

  async pushBranch() {
    this.log(`Pushing branch ${this.branchName} to origin...`);
    
    try {
      execSync(`git push -u origin ${this.branchName}`, {
        cwd: this.workingDir,
        stdio: 'pipe'
      });
      this.log('Branch pushed successfully');
    } catch (error) {
      throw new Error(`Failed to push branch: ${error.message}`);
    }
  }

  async createPullRequest(title, description) {
    this.log('Creating pull request...');
    
    // For this implementation, we'll create a PR description file
    // In a real GitHub Actions environment, this would use the GitHub CLI or API
    
    const prData = {
      title,
      description,
      head: this.branchName,
      base: this.targetBranch,
      timestamp: new Date().toISOString()
    };

    // Save PR data for the GitHub Actions workflow to use
    const prPath = path.join(this.workingDir, 'guardian-pr.json');
    fs.writeFileSync(prPath, JSON.stringify(prData, null, 2));
    
    // In a real implementation, we would make an API call here:
    // const response = await octokit.pulls.create({
    //   owner: context.repo.owner,
    //   repo: context.repo.repo,
    //   title,
    //   body: description,
    //   head: this.branchName,
    //   base: this.targetBranch
    // });

    // For demo purposes, we'll simulate the PR creation
    const mockPRNumber = Math.floor(Math.random() * 1000) + 1;
    
    this.log(`Pull request created: #${mockPRNumber}`);
    this.log(`Title: ${title}`);
    
    // Output for GitHub Actions
    console.log(`::set-output name=pr_number::${mockPRNumber}`);
    console.log(`::set-output name=pr_url::https://github.com/aikyabarot/frontend/pull/${mockPRNumber}`);
    
    return {
      number: mockPRNumber,
      url: `https://github.com/aikyabarot/frontend/pull/${mockPRNumber}`,
      title,
      description
    };
  }

  async run() {
    try {
      this.log('Starting PR creation...');
      
      if (!this.branchName) {
        throw new Error('No branch name provided');
      }

      const reports = this.loadGuardianReports();
      const title = this.generatePRTitle(reports);
      const description = this.generatePRDescription(reports);
      
      await this.pushBranch();
      const pr = await this.createPullRequest(title, description);
      
      // Save PR info for auto-merge phase
      const prInfo = {
        ...pr,
        branch: this.branchName,
        target: this.targetBranch,
        timestamp: new Date().toISOString(),
        reports
      };
      
      fs.writeFileSync('guardian-pr-info.json', JSON.stringify(prInfo, null, 2));
      
      this.log('PR creation completed successfully');
      return prInfo;
    } catch (error) {
      this.log(`PR creation failed: ${error.message}`, 'error');
      throw error;
    }
  }
}

// CLI handling
function parseArgs() {
  const args = process.argv.slice(2);
  const options = {};
  
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    const value = args[i + 1];
    options[key] = value;
  }
  
  return options;
}

// Run if called directly
if (require.main === module) {
  const options = parseArgs();
  const creator = new GuardianPRCreator(options);
  
  creator.run().catch(error => {
    console.error('PR creation failed:', error);
    process.exit(1);
  });
}

module.exports = GuardianPRCreator;